# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Swagger Specification for electronic clinical quality measure calculation
#
# Copyright (c) 2016.  The MITRE Corporation. All rights reserved.
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
swagger: '2.0'

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                  API Information
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
info:
  version: "0.1.0"
  title: eCQM REST API
  description: |
    eCQM description goes here
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   Host, service Base Path, Schemes and Content Types
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
schemes:
  - http
  - https
produces:
  - application/json
consumes:
  - application/json

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#           Paths
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
paths:
  /QualityReport:
    post:
      operationId: createQualityReport
      summary: Create or find a quality report
      tags:
        - QualityReport
      parameters:
        - name: qualityReport
          in: body
          description: Record Match Context to add
          required: true
          schema:
            $ref: '#/definitions/QualityReport'
      responses:
        200:
          description: |
            If the quality report exists, for the posted measureId, subId (if
            provided) and effectiveDate, it will be returned. Otherwise a new
            quality report will be created. The status of this report can be
            polled by extracting the id from the provided JSON and performing
            a GET
        400:
          description: Bad Request
        500:
          description: Internal Server Error

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                       Definitions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
definitions:
  QualityReport:
    type: object
    description: |
      A Quality Report is the result of an electronic Clinical Quality Measure
      calculation.
    required:
    - measureId
    - effectiveDate
    properties:
      id:
        type: string
      npi:
        type: string
      status:
        type: object
        properties:
          state:
            type: string
            enum:
            - requested
            - completed
          log:
            type: array
      measureId:
        type: string
      subId:
        type: string
      effectiveDate:
        type: integer
        description: |
          The effectiveDate is the end of the measure period for the purposes of
          eCQM calculation. It is represented in seconds since January 1, 1970
          (Unix time).
      result:
        $ref: '#/definitions/QualityReportResult'
    example:
      status:
        state: completed
      effectiveDate: 1420088400
      measureId: 40280381-4C18-79DF-014C-2E72BD870D38
      result:
        populationIds:
          denominator: 48764B33-6FA5-4418-B131-06D9A9012FB2
          numerator: 0E69D381-A7E7-4063-BA85-C5859B7B3A12
        denominator: 23
        numerator: 17
  QualityReportResult:
    type: object
    description: |
      The totals for a clinical quality measure calculation along with
      the population ids
    properties:
      populationIds:
        $ref: "#/definitions/PopulationIDs"
      initialPatientPopulation:
        type: integer
      denominator:
        type: integer
      exception:
        type: integer
      exclusion:
        type: integer
      numerator:
        type: integer
      antinumerator:
        type: integer
      measurePopulation:
        type: integer
      observation:
        type: number
        format: float32
  PopulationIDs:
    type: object
    description: |
      The HQMF identifiers for the measure populations
    properties:
      initialPatientPopulation:
        type: string
      denominator:
        type: string
      exception:
        type: string
      exclusion:
        type: string
      numerator:
        type: string
      measurePopulation:
        type: string
      observation:
        type: string
